---
- name: Install pinned datadog-agent package
  dnf:
    name: "datadog-agent-{{ datadog_agent_redhat_version }}"
    update_cache: yes
    state: present
    allow_downgrade: "{{ datadog_agent_allow_downgrade }}"
  register: datadog_agent_install
  when: not ansible_check_mode
  notify: restart datadog-agent
